# Generated by Django 3.2.7 on 2021-09-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_testing', '0002_studentnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentnumber',
            old_name='staff_id',
            new_name='student_id',
        ),
    ]
