# Generated by Django 3.2.7 on 2021-10-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_limit', models.CharField(blank=True, max_length=30)),
                ('accessible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('attendance', models.ManyToManyField(blank=True, related_name='attendance', to='attendance.Attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('courses', models.ManyToManyField(related_name='courses', to='attendance.Course')),
            ],
        ),
        migrations.CreateModel(
            name='MarkAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(related_name='lecturer_courses', to='attendance.Course')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendances',
            field=models.ManyToManyField(blank=True, related_name='attendances', to='attendance.MarkAttendance'),
        ),
    ]
